version: "3.9"

services:
  bppweb:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: pyxelchain.com
      LETSENCRYPT_HOST: pyxelchain.com
      LETSENCRYPT_EMAIL: admin@royalprotocol.io
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        
networks:
  default:
    name: nginx-proxy        