name: ci_cd for pyxelchain.com

on:
  push:
    branches: [main]
    
env:
  USERNAME: ubuntu
  REMOTE_FOLDER: ~/websites/pyxelchain_website
  
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_BPPAPI_HOST: bppapi-staging.gameficap.com
      - name: Build the code
        uses: actions/setup-node@v3
        with:
          node-version:  16.16.x
          cache: npm
          cache-dependency-path: package-lock.json
      - run: pwd && ls -la && cat .env && sudo cp env_latest.txt .env && node --version && npm --version && npm i --legacy-peer-deps && npm run export && ls -lrt
      - name: Upload file to bucket
        uses: a-sync/s3-uploader@master
        with:
          args: --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          S3_BUCKET: 'pyxelchain-website-prod'
          FILE: ./out

  invalidate:
    needs: build_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      - name: Invalidate CloudFront Cache
        run: | 
          echo "Invalidating Cloudfront Distribution"
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_PROD }} --paths "/*"          




      # - name: Copy Files to Remote Host
      #   uses: Pendect/action-rsyncer@v1.1.0
      #   env:
      #     DEPLOY_KEY: ${{ secrets.PRIVATE_KEY }}
      #   with:
      #     flags: '-avzr'
      #     options: ''
      #     ssh_options: ''
      #     src: ''
      #     dest: '$USERNAME@${{ secrets.PROD_HOST }}:$REMOTE_FOLDER'
      # - name: Deploy on Remote Host
      #   uses: fifsky/ssh-action@master
      #   with:
      #     command: |
      #       pwd && cd websites/pyxelchain_website && cp env_latest.txt .env && cp -r DevOps/* . && ls -lrt && docker-compose -f docker-compose-prod.yml up -d --build 
      #     host: ${{ secrets.PROD_HOST }}
      #     user: $USERNAME
      #     key: ${{ secrets.PRIVATE_KEY }}
